- id: "1638934686700"
  alias: Christmas On
  description: Turn christmas scene on with sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "30"
      id: sun_down_plus_30
  condition: []
  action:
    - scene: scene.christmas_on
  mode: single
- id: "1638935651028"
  alias: Christmas Off
  description: Turn christmas off at configured time
  trigger:
    - platform: time
      at: 00:00:00
      id: midnight
  condition: []
  action:
    - scene: scene.christmas_off
  mode: single
