- platform: template
  sensors:
    # Outdoor Weather
    autohouse_outdoor_temperature:
      friendly_name: "AutoHouse Outdoor Temperature"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('weather.autohouse', 'temperature') }}"

    autohouse_weather_humidity:
      friendly_name: "AutoHouse Outdoor Humidity"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('weather.autohouse', 'humidity') }}"

    hvac_fan_mode:
      friendly_name: "Hvac Fan Mode"
      value_template: "{{ state_attr('climate.main_floor', 'fan_mode') }}"
      icon_template: mdi:fan
