- platform: template
  sensors:
    # Outdoor Weather
    autohouse_outdoor_temperature:
      friendly_name: "AutoHouse Outdoor Temperature"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('weather.autohouse', 'temperature') }}"

    autohouse_weather_humidity:
      friendly_name: "AutoHouse Outdoor Humidity"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('weather.autohouse', 'humidity') }}"

    # Outdoor/Indoor Dewpoint Differences
    crawlspace_nw_dewpoint_difference:
      friendly_name: "Crawlspace NW Dewpoint Difference"
      unit_of_measurement: "°C"
      value_template: >
        {% set inside = states('sensor.crawlspace_nw_thp_thermal_comfort_dew_point') | float %}
        {% set outside = states('sensor.outdoor_thermal_comfort_dew_point') | float %}
        {{ ((inside - outside)) | round(1, default=0) }}

    crawlspace_ne_dewpoint_difference:
      friendly_name: "Crawlspace NE Dewpoint Difference"
      unit_of_measurement: "°C"
      value_template: >
        {% set inside = states('sensor.crawlspace_ne_thp_thermal_comfort_dew_point') | float %}
        {% set outside = states('sensor.outdoor_thermal_comfort_dew_point') | float %}
        {{ ((inside - outside)) | round(1, default=0) }}

    crawlspace_sw_dewpoint_difference:
      friendly_name: "Crawlspace SW Dewpoint Difference"
      unit_of_measurement: "°C"
      value_template: >
        {% set inside = states('sensor.crawlspace_sw_thp_thermal_comfort_dew_point') | float %}
        {% set outside = states('sensor.outdoor_thermal_comfort_dew_point') | float %}
        {{ ((inside - outside)) | round(1, default=0) }}

    crawlspace_se_dewpoint_difference:
      friendly_name: "Crawlspace SE Dewpoint Difference"
      unit_of_measurement: "°C"
      value_template: >
        {% set inside = states('sensor.crawlspace_se_thp_thermal_comfort_dew_point') | float %}
        {% set outside = states('sensor.outdoor_thermal_comfort_dew_point') | float %}
        {{ ((inside - outside)) | round(1, default=0) }}

    # Dewpoint PID setpoint
    crawlspace_t_setpoint_dewpoint_difference:
      friendly_name: "Crawlspace Setpoint Dewpoint Difference"
      unit_of_measurement: "°C"
      value_template: >
        {% set T_setpoint = states('input_number.crawlspace_temperature_set_point') | float %}
        {% set dewpoint = states('sensor.crawlspace_dewpoint_max') | float %}
        {% set offset = states('input_number.crawlspace_dewpoint_setpoint_offset') | float %}
        {{ ((dewpoint - (T_setpoint - offset))) | round(1, default=0) }}

- platform: pid_controller
  name: crawlspace_vent_fan_controller
  set_point: 0
  invert: yes
  p: 10
  i: 0.001
  d: 0
  entity_id: sensor.crawlspace_t_setpoint_dewpoint_difference
  minimum: 0
  maximum: 5
  sample_time: 10
  windup: 0.1
